const fs = require('fs');
const path = require('path');
const glob = require('glob'); // Need to check if glob is installed, but we can just use native fs or simple recursion since we know the directory structure.

const baseDir = '/home/nithish/.gemini/antigravity/scratch/voyageai-frontend/public/data/destinations/India';

const PATCHES = {
  'ahmedabad': {
    'topAttractions': [
      {'name':'Sabarmati Ashram (Gandhi Ashram)','description':'Mahatma Gandhi lived here from 1917-1930. From here he launched the Salt March (Dandi March) on March 12, 1930. The museum contains his personal belongings, letters, and a diorama of the Salt March. One of the most moving museums in India. Entry free. Open daily 8:30AM-6:30PM.','location':'Ashram Road, along Sabarmati River'},
      {'name':'Adalaj Step Well (Vav)','description':'A stunning 5-storey octagonal step well (1498 CE) built by Queen Rudabai of the Vaghela dynasty, blending Hindu and Islamic architectural elements. The well descends 4 storeys with intricately carved walls, pavilions, and serpentine designs. Best in morning light when sun illuminates the depths. Entry: Free.','location':'Adalaj village, 18km from Ahmedabad'},
      {'name':'Sidi Saiyyed Mosque (Jali Windows)','description':'A 1573 mosque famous for its extraordinary stone jali (lattice) windows depicting the Tree of Life — intertwining branches and leaves in detailed stone carving. The image of these windows became the logo of the Indian Institute of Management Ahmedabad. One of the finest examples of stone lattice work in the world.','location':'Lal Darwaza, Central Ahmedabad'},
      {'name':'Akshardham Temple Gandhinagar','description':'A magnificent Hindu temple complex (1992) in the neighboring state capital Gandhinagar (23km), featuring 97m-long carvings of over 200 scenes from Indian scriptures, 9 domes, 208 ornamental pillars. The spiritual complex also includes an exhibition on the life of Swaminarayan.','location':'Gandhinagar, 23km from Ahmedabad'},
      {'name':'Calico Museum of Textiles','description':'One of the finest textile museums in the world — housing 6 centuries of Indian textiles including Mughal royal fabrics, temple textiles, and regional weaving traditions. By appointment only (morning and afternoon sessions). Entry: Free by appointment. Considered the most important textile collection in Asia.','location':'Shahibaug, North Ahmedabad'},
      {'name':'Kankaria Lake','description':'A 15th-century artificial lake (1451 CE) built by Sultan Qutbuddin Ahmedshah II, 2km in circumference. The Nagina Wadi island in the center houses a zoo. A popular recreational spot with a heritage walk around the perimeter, toy train, and Balvatika children\'s park.','location':'Maninagar, South Ahmedabad'}
    ]
  },
  'kovalam': {
    'topAttractions': [
      {'name':'Lighthouse Beach','description':'The most popular beach in Kovalam, anchored by the iconic red-and-white Vizhinjam Lighthouse (1972). The rocky promontory with the lighthouse provides the best views. Swimming is relatively safe in the inner bay. The beach is lined with a cliff-walk promenade, cafes, and ayurvedic massage parlors.','location':'Central Kovalam'},
      {'name':'Hawa Beach (Eve\'s Beach)','description':'The northernmost of Kovalam\'s three beaches, separated from Lighthouse Beach by a rocky headland. Calmer water than Lighthouse Beach, popular with families. Slightly less commercialized, with fewer tourists.','location':'Northern Kovalam'},
      {'name':'Samudra Beach','description':'The quietest of Kovalam\'s beaches, reserved primarily for the Leela hotel\'s guests. Rocky shoreline, clearer water. The Leela\'s cliff-top infinity pool overlooking this beach is iconic.','location':'1km north of Lighthouse Beach'},
      {'name':'Vizhinjam Juma Masjid & Rock Caves','description':'An 8th-century rock-cut cave temple (Vizhinjam, 2km from Kovalam) with the oldest surviving example of Kerala sculpture — a partially completed half-relief of Shiva. Also near the ancient Vizhinjam Port (now being developed as India\'s first deep-water transshipment port).','location':'Vizhinjam, 2km from Kovalam'},
      {'name':'Ayurvedic Resorts & Treatments','description':'Kovalam is one of India\'s premier Ayurveda destinations — numerous certified centers offer Panchakarma (5-day detox treatments), Abhyangam massage (₹800-2000/session), Shirodhara (oil drip on forehead), and Nasya. The best: SwaSwara, Niraamaya, and Kairali. Multi-day residential programs from ₹5000/day.','location':'Throughout Kovalam cliff area'},
      {'name':'Vizhinjam International Seaport (Construction)','description':'India\'s first internationally competitive transshipment port under construction by Adani Group (2025 completion). The development has transformed Vizhinjam from a sleepy fishing village. The fishing harbor at Vizhinjam with hundreds of colorful boats and fishermen is photogenic in the early morning.','location':'Vizhinjam, 2km from Kovalam'}
    ]
  },
  'aurangabad': {
    'topAttractions': [
      {'name':'Ajanta Caves (UNESCO) — Day Trip','description':'30 Buddhist cave monasteries and temples (1st BCE – 5th CE) carved into horseshoe-shaped cliffs 107km from Aurangabad. Caves 1 and 2 have the finest painted murals in the world — detailed court scenes, Jataka tales, and the life of the Buddha painted with extraordinary skill 2,000 years ago. Entry: ₹40 (Indian), ₹600 (foreign). Open Tue-Sun.','location':'107km from Aurangabad'},
      {'name':'Ellora Caves (UNESCO) — Day Trip','description':'34 rock-cut temples (Buddhist, Hindu, Jain, 6th-11th century CE) covering 2km of cliff face 30km from Aurangabad. The Kailasa Temple (Cave 16) — dedicated to Shiva, carved from a single basalt rock by 7,000 laborers over 150 years — is the largest single rock-cut structure in the world (83m × 47m × 33m). Entry: ₹40 (Indian), ₹600 (foreign).','location':'30km from Aurangabad'},
      {'name':'Bibi Ka Maqbara','description':'A 1679 CE Mughal tomb built by Aurangzeb\'s son Azam Shah for his mother Dilras Banu Begum — called the "Taj of the Deccan" or "Mini Taj" for its white marble and resemblance to the Taj Mahal. The marble was imported from Rajasthan, the rest in lime plaster. Entry: ₹25 (Indian), ₹300 (foreign).','location':'North Aurangabad'},
      {'name':'Daulatabad Fort (Deogiri)','description':'A virtually impregnable 13th-century fort on a 200m high volcanic cone 15km from Aurangabad. Built by the Yadava dynasty, later strengthened by the Delhi Sultanate and Muhammad bin Tughluq (who briefly moved the entire Delhi capital here in 1327). The spiral interior moat and the dark tunnel (requiring a candle) are extraordinary. Entry: ₹25 (Indian), ₹300 (foreign).','location':'15km from Aurangabad'},
      {'name':'Aurangabad Caves','description':'A group of 12 Buddhist rock-cut caves (6th-8th CE) in two groups — the best preserved in Maharashtra apart from Ajanta-Ellora. Cave 3 has a remarkable 10-arm standing Bodhisattva and Cave 7 has elaborate carvings. Less visited than the famous UNESCO sites, making for a peaceful visit. Entry: ₹25 (Indian).','location':'3km north of Aurangabad city'},
      {'name':'Panchakki (Water Mill)','description':'A 17th-century underground water channel system that drove a massive millstone to grind grain for the Dargah of Hazrat Baba Shah Musafir Chishti. The waterfall created by the channel and the scenic garden complex are beautiful. The Dargah itself is an active Sufi shrine.','location':'Begumpura, Central Aurangabad'}
    ]
  },
  'lonavala': {
    'topAttractions': [
      {'name':'Karla Caves','description':'The finest rock-cut Buddhist cave temples in Maharashtra — a 2nd BCE Buddhist site with the best-preserved Chaitya (prayer hall) in India. The great Chaitya has a 15m high carved wooden ribbed roof, 38 octagonal pillars, and an Ashoka-era stupa inside. 12km from Lonavala. Entry: ₹25 (Indian), ₹300 (foreign).','location':'12km from Lonavala'},
      {'name':'Bhaja Caves','description':'Similar in age to Karla (2nd BCE), these 22 Buddhist rock-cut caves are less visited but equally beautiful. The dancing couple and musician carvings at the entrance to Cave 19 are remarkable. 12km from Lonavala (1km walk from Karla). Entry: ₹25 (Indian).','location':'13km from Lonavala'},
      {'name':'Tiger\'s Leap (Tiger Point)','description':'A dramatic cliff viewpoint overlooking the Sahyadri valley 650m below — named for a rock formation resembling a tiger\'s head. One of the finest viewpoints in the Western Ghats, best in monsoon when the valley fills with mist and waterfalls. 11km from Lonavala. Entry: ₹20.','location':'11km from Lonavala'},
      {'name':'Rajmachi Fort','description':'A twin-peaked Maratha hill fort (17th century) with two ramparts — Shrivardhan and Manaranjan — accessible by 15km trek from Karjat or 21km from Lonavala. The fort sits on a strategic point in the Sahyadri range with 360-degree views. Overnight camping (₹300-500) is popular.','location':'21km from Lonavala (via Tungarli)'},
      {'name':'Bhushi Dam','description':'A small dam on the Indrayani River most famous during monsoon (June-September) when excess water overflows the concrete steps in a series of natural waterfalls. Extremely popular with Mumbai and Pune visitors — becomes crowded on weekends. Strong currents during heavy monsoon.','location':'3km from Lonavala town'},
      {'name':'Duke\'s Nose (Naagphani)','description':'A pointed rock formation resembling a duck\'s nose (also called Naagphani — Cobra\'s Hood) — a prominent viewpoint 7km from Lonavala. Trekking route around the ridge. Visible from the Mumbai-Pune Expressway.','location':'7km from Lonavala'}
    ]
  },
  'mahabaleshwar': {
    'topAttractions': [
      {'name':'Venna Lake','description':'A 28-acre artificial lake in the heart of Mahabaleshwar town, created in 1842 by Mr. Lodwick. Boating (₹150-250/30 min), horse rides on the shore (₹200-400), and garden walkways. The best morning activity.','location':'Central Mahabaleshwar'},
      {'name':'Elephant Head Point (Needle Hole Point)','description':'A dramatic cliff viewpoint where two rock formations resemble an elephant\'s head and trunk extending over the valley. One of Mahabaleshwar\'s most photographed viewpoints. 6km from town.','location':'6km from Mahabaleshwar town'},
      {'name':'Wilson Point (Sunrise Point)','description':'The highest point in Mahabaleshwar (1439m) — the only place where both sunrise and sunset are visible. Dawn views across the Sahyadri plateau are breathtaking. 2km from town.','location':'2km north of Mahabaleshwar'},
      {'name':'Mapro Garden (Strawberry Farm)','description':'A strawberry and fruit products company with a beautiful garden café (1.5km from town). Mahabaleshwar produces 85% of India\'s strawberries. Fresh strawberry with cream (₹80-150), strawberry jam, crushes, and wine on sale. The most popular stop in Mahabaleshwar.','location':'1.5km from Mahabaleshwar on Panchgani road'},
      {'name':'Lingmala Waterfall','description':'The most dramatic waterfall near Mahabaleshwar — a 600-foot (180m) cascading waterfall in a protected forest, 6km from town. A 20-minute downhill trek through thick forest leads to the base. Best in and after monsoon (July-October). Entry: ₹40.','location':'6km from Mahabaleshwar'},
      {'name':'Pratapgarh Fort (Day Trip)','description':'A magnificent Maratha hilltop fort (1656 CE) built by Shivaji Maharaj on a spur of the Sahyadri 24km from Mahabaleshwar, at 1080m. The site of the famous Afzal Khan killing (1659). Two imposing gates, towers, and a Bhavani Temple inside. Trekking route from the base village.','location':'24km from Mahabaleshwar'}
    ]
  },
  'nashik': {
    'topAttractions': [
      {'name':'Trimbakeshwar Temple','description':'One of India\'s 12 sacred Jyotirlinga Shiva temples (self-manifested Shiva shrines), 28km from Nashik at the source of the Godavari River. The 18th-century black stone temple is surrounded by the Brahmagiri mountain. The Godavari begins as a small spring at Brahmagiri\'s peak (6km difficult trek). Kumbh Mela (Simhastha) held here every 12 years.','location':'28km from Nashik, Trimbak town'},
      {'name':'Sula Vineyards','description':'India\'s most celebrated winery — producing award-winning Dindori Sula Riesling, Sula Shiraz, and other varietals on 2,400 acres. The region\'s microclimate (similar to Provence) makes the Nashik valley India\'s Napa Valley. Wine tastings (₹300-800), vineyard tours, the Beyond by Sula resort. Most popular: February harvest season.','location':'15km from Nashik city, Dindori Road'},
      {'name':'Pandav Leni Caves (Nashik Caves)','description':'24 Buddhist rock-cut caves (2nd BCE – 6th CE) carved into a basalt hillside 8km from Nashik, housing 10th-century inscriptions, water cisterns, and Hinayana-era chaitya halls. Entry: ₹25 (Indian), ₹300 (foreign).','location':'8km from Nashik city'},
      {'name':'Ramkund (Holy Tank)','description':'A sacred bathing ghat on the Godavari River where Lord Rama is believed to have bathed during his exile. Hindus scatter ashes of deceased family members here believing it grants moksha. The riverside is lined with ghats, temples, and brahmin priests. Most active during the Simhastha Kumbh Mela.','location':'Panchavati, Central Nashik'},
      {'name':'Anjaneri Hill (Hanuman Birthplace)','description':'A 4489-foot (1369m) hill 16km from Nashik believed to be the birthplace of Lord Hanuman. The 6km trek up passes ancient temples. Clear days offer views of Brahmagiri, Harihar Fort, and the Nashik valley.','location':'16km from Nashik'},
      {'name':'Wine Trail — Soma, Vallonne, York Winery','description':'Apart from Sula, Nashik has 80+ wineries including Soma (award-winning Chenin Blanc), Vallonne (boutique French-style), and York Winery (hillside, luxury). Most offer tastings (₹300-500/session) and farm-to-table lunches. Best visited February-April (harvest season, grapes on the vine).','location':'Dindori Road wine corridor, 15-25km from Nashik'}
    ]
  },
  'shirdi': {
    'topAttractions': [
      {'name':'Samadhi Mandir (Main Shrine)','description':'The white marble shrine built over the tomb (samadhi) of Sai Baba of Shirdi (died 1918). A life-size white Italian marble statue of Sai Baba sits in the sanctum. The pilgrims\' queue (darshan line) can be 2-8 hours. VIP darshan passes available (₹300-500). The Sai Baba Sansthan Trust serves 50,000+ pilgrims daily.','location':'Dwarkamai Road, central Shirdi'},
      {'name':'Dwarkamai Mosque','description':'The mosque where Sai Baba lived for 60 years until his death in 1918. A fire (dhuni) has been burning here continuously since Sai Baba lit it. His personal items — grinding stone, iron pot, wooden plank he slept on — are preserved here. The sacred mosque accepts all religions. Entry: Free.','location':'Adjacent to Samadhi Mandir'},
      {'name':'Chavadi','description':'A small hall where Sai Baba slept every alternate night. His palanquin is preserved here and taken out in procession on Thursday evenings. One of the key pilgrimage stops.','location':'100m from Dwarkamai'},
      {'name':'Lendi Baug (Garden)','description':'A garden planted by Sai Baba himself where he daily watered the plants and tended the trees. He would also meditate under a Neem tree here. Now a maintained garden with the lamp (deep) that Sai Baba kept burning and a small temple.','location':'400m from Samadhi Mandir'},
      {'name':'Shri Saibaba Museum','description':'A museum containing Sai Baba\'s personal belongings — his satka (staff), blanket, books, and photographs. The museum traces his life from arriving in Shirdi as a young man to his Mahasamadhi in 1918.','location':'Near Samadhi Mandir, Shirdi'},
      {'name':'Khandoba Temple','description':'The temple of Khandoba (a manifestation of Shiva) on the edge of Shirdi where Sai Baba first arrived as a young man. The priest Mhalsapati greeted him with "Ya Sai!" (Welcome, Saint!) — the origin of the name "Sai Baba". An important first stop for pilgrims.','location':'500m from Samadhi Mandir'}
    ]
  },
  'ajmer': {
    'topAttractions': [
      {'name':'Dargah Sharif of Moinuddin Chishti','description':'The shrine of Hazrat Khwaja Moinuddin Chishti (1141-1230) — the most important Sufi shrine in India and one of the most visited religious sites in the subcontinent, receiving millions of devotees of all faiths annually. Emperor Akbar walked barefoot from Agra to Ajmer to seek the saint\'s blessings. Large silver doors, qawwali music in the courtyards. Entry: Free (Dargah lane bazaars have flower/chadar sellers).','location':'Dargah Bazaar, central Ajmer'},
      {'name':'Ana Sagar Lake','description':'A 12th-century artificial lake (1135-1150 CE) constructed by Anaji Chahamana, grandfather of Prithviraj Chauhan. The 13km perimeter embankment (Bandh) has Mughal-era pavilions (Baradari) built by Shah Jahan. A pleasant evening walk with Daulat Bagh gardens.','location':'Northwest Ajmer'},
      {'name':'Adhai Din Ka Jhonpra','description':'A spectacular ruined mosque (1193 CE) built in 2.5 days by Qutb ud-Din Aibak on the site of a Sanskrit college — the oldest mosque in Rajasthan, with intricate calligraphy in its arches. The name ("Two and a Half Day Hut") comes from the legendary speed of construction.','location':'Behind Dargah, 1km'},
      {'name':'Taragarh Fort (Star Fort)','description':'A 14th-century fort (1354 CE) above Ajmer on the Taragarh hill, offering magnificent views of the city, Ana Sagar Lake, and the surrounding Aravalli range. The fort is largely ruined but the climb is rewarding. The shrine of Miran Sahib (a famous soldier-saint) is inside.','location':'2km from Dargah, hilltop'},
      {'name':'Akbar\'s Palace Museum','description':'A 16th-century Mughal palace built by Emperor Akbar as his administrative headquarters during his campaigns in Rajputana. Now an archaeological museum with Mughal artifacts. The building itself — with its large courtyard, thick walls, and distinctive Mughal style — is historically significant.','location':'Near Dargah Bazaar'},
      {'name':'Pushkar (14km)','description':'The sister sacred city 14km from Ajmer — one of the world\'s few Brahma temples, the sacred Pushkar Lake with 52 bathing ghats, and the famous annual Camel Fair (November). The two cities are almost always visited together. A taxi from Ajmer to Pushkar takes 30 minutes.','location':'14km from Ajmer via Pushkar road'}
    ]
  },
  'bikaner': {
    'topAttractions': [
      {'name':'Junagarh Fort','description':'One of the finest forts in Rajasthan (1593 CE, built by Raja Rai Singh), never conquered despite multiple attacks. 37 palaces, temples, and pavilions inside the 5.28-acre complex — Anup Mahal (red sandstone with gold filigree), Phool Mahal, Badal Mahal, and the Karan Mahal. The Indian Air Force museum section has a vintage WWII biplane. Entry: ₹100 (Indian), ₹500 (foreign).','location':'Central Bikaner'},
      {'name':'Karni Mata Temple (Rat Temple)','description':'A revered temple 30km south at Deshnok dedicated to Karni Mata (a 15th-century mystic). Over 25,000 rats (kabas) live here and are considered sacred — believed to be reincarnated devotees awaiting rebirth as humans. White rats are especially auspicious. Pilgrims walk barefoot on rat-infested floors. Entry: ₹10 (Indian), ₹50 (foreign, without camera).','location':'Deshnok, 30km from Bikaner'},
      {'name':'Lalgarh Palace','description':'A magnificent Indo-Saracenic palace complex built by Maharaja Ganga Singh in 1902 using local pink sandstone and Belgian glass. Now partly a heritage hotel (Laxmi Niwas Hotel), partly the Sadul Museum with royal portraits, hunting trophies, and vintage photographs.','location':'Northern Bikaner'},
      {'name':'National Research Centre on Camel','description':'India\'s only camel research center, 8km from Bikaner — home to 300+ camels of different breeds including the Bikaneri breed (best for carrying loads). Camel rides, camel milk tasting (₹30/glass, claimed to have medicinal properties). A unique and educational visit.','location':'8km from Bikaner, Jorbeer'},
      {'name':'Bikaneri Bhujia & Food Trail','description':'Bikaner is the birthplace of Bhujia namkeen — crispy spiced moth bean noodles that became a national snack. Original Haldiram\'s started here. The Kote Gate area has dozens of competing bhujia manufacturers. Visit the old city bhujia markets and buy directly from traditional makers (₹150-500/kg, far better than packaged).','location':'Kote Gate area, old city'},
      {'name':'Gajner Palace & Gajner Wildlife Sanctuary','description':'A 32km drive from Bikaner brings you to this former Maharaja of Bikaner hunting lodge (1884) on the shores of Gajner Lake — now a heritage hotel. The Gajner Wildlife Sanctuary has blackbuck, chinkara, and wild boar. The lake attracts imperial sandgrouse (thousands in winter) and flamingos.','location':'32km from Bikaner on NH15'}
    ]
  },
  'chittorgarh': {
    'topAttractions': [
      {'name':'Chittorgarh Fort (UNESCO)','description':'The largest fort complex in India and Asia — 700 acres, 13km perimeter, accessed by 7 gates (pols). Built in the 7th century CE, it contains palaces, temples, towers, and reservoirs. Three Jauhars (mass self-immolations by Rajput women facing defeat) took place here in 1303, 1535, and 1568. Entry: ₹40 (Indian), ₹600 (foreign). Open sunrise to sunset.','location':'Chittor city, on a 180m plateau'},
      {'name':'Vijay Stambha (Tower of Victory)','description':'A 37m tall victory tower (1448 CE) built by Rana Kumbha to commemorate his victory over the combined forces of Gujarat and Malwa. Densely carved with Hindu sculptures on all 9 floors — the best carvings in Rajasthan. Can climb to the top for views. Entry included in fort ticket.','location':'Inside Chittorgarh Fort'},
      {'name':'Kirti Stambha (Tower of Fame)','description':'An earlier 22m Jain victory tower (12th century CE) dedicated to Rishabhadeva (first Jain Tirthankara). The five-storey tower is covered in naked Jain figures. The oldest monument in the fort complex, predating the Rajput rule.','location':'Inside Chittorgarh Fort'},
      {'name':'Rani Padmini\'s Palace','description':'The lake palace (13th century) at the far end of the fort where Queen Padmini (Padmavati) allegedly lived. Legend has it that Alauddin Khilji glimpsed her reflection in a mirror and besieged the fort in 1303. Padmini and 16,000 women performed the first Jauhar here. The lotus pool is serene.','location':'Inside Chittorgarh Fort (far end)'},
      {'name':'Meera Bai Temple','description':'A temple inside the fort dedicated to Meera Bai (1498-1557), the Rajput princess-poet-saint who devoted her life to Krishna, defying social norms. Her bhajans (devotional songs) are still sung across India. The small temple where she worshipped Krishna is deeply moving.','location':'Inside Chittorgarh Fort'},
      {'name':'Gaumukh Reservoir','description':'A natural spring and reservoir (Gau Mukh = Cow\'s Mouth) from which water emerges from a stone spout shaped like a cow\'s head. The 12th-century reservoir sustained the fort during sieges. The peaceful setting in a rocky ravine has a small Shiva shrine.','location':'Inside Chittorgarh Fort (north end)'}
    ]
  },
  'mount-abu': {
    'topAttractions': [
      {'name':'Dilwara Jain Temples','description':'Widely regarded as the finest example of marble carving in the world — a complex of 5 Jain temples (11th-13th century CE). The Vimala Vasahi (1031 CE) and Luna Vasahi (1230 CE) are the finest, with incredible intricacy in the pillars, domes, and sculptures — the ceiling medallions took 14 years each to carve. No photography permitted inside. Entry: Free (donations welcome). Open 12PM-6PM daily.','location':'5km from Mount Abu town'},
      {'name':'Nakki Lake','description':'A sacred lake (1200m altitude) at the center of Mount Abu town, legend says excavated by the gods with their nails (nakh in Hindi, hence Nakki). Boating available (₹150/30 min). The Toad Rock formation overlooking the lake is a climbing spot.','location':'Central Mount Abu'},
      {'name':'Guru Shikhar','description':'At 1722m, the highest peak in the Aravalli Range and the highest point in Rajasthan. A 15km drive from town followed by 300 steps. The Guru Dattatreya temple at the top is ancient. Views extend to Gujarat on clear days.','location':'15km from Mount Abu town'},
      {'name':'Achalgarh Fort','description':'A 14th-century fort (1452 CE) built by Rana Kumbha, with the Achaleshwar Mahadev Temple (ancient Shiva temple with footprint of Lord Shiva and a natural Shiva lingam). Mandakini and Agni Kund lakes are nearby.','location':'11km from Mount Abu town'},
      {'name':'Sunset Point','description':'The most popular viewpoint in Mount Abu — a terraced hillside looking west towards the Gujarat plains. Becomes extremely crowded at sunset (October-March). Horse rides to the point (₹200-400). Despite the crowds, the sunsets over the Aravalli plains are genuinely magnificent.','location':'4km from Mount Abu town'},
      {'name':'Wildlife Sanctuary (Trevor\'s Tank)','description':'A 288 sq km wildlife sanctuary surrounding Mount Abu — home to leopards, sambar, crocodiles (at Trevor\'s Tank — a crocodile viewing point 5km from town). The sanctuary has excellent birdwatching: paradise flycatcher, grey jungle fowl, painted spurfowl.','location':'Throughout the Mount Abu area (sanctuary)'}
    ]
  },
  'pushkar': {
    'topAttractions': [
      {'name':'Brahma Temple','description':'One of the very few temples in the world dedicated to Brahma the Creator (other major Brahma temples are at Khokhan in HP and Asotra in Rajasthan). The 14th-century marble temple with a distinctive red shikara is in the center of Pushkar town. Non-Hindus are permitted. Entry: Free. Strict rules: no leather products, no photography inside.','location':'Central Pushkar'},
      {'name':'Pushkar Lake (52 Ghats)','description':'A sacred lake believed to have formed from a lotus petal dropped by Brahma. 52 bathing ghats (stone steps) line the lake — Brahma Ghat (most sacred), Gau Ghat, VIP Ghat. Bathing is believed to wash away sins. Sunset and sunrise on the ghats are profoundly beautiful. No non-vegetarian food and no alcohol are served anywhere near the lake.','location':'Central Pushkar'},
      {'name':'Savitri Temple','description':'A hilltop temple dedicated to Brahma\'s wife Savitri — the reason Brahma has few temples (she cursed him for using Gayatri in her place at the Pushkar yajna). The 3km climb up Ratnagiri Hill (1.5 hrs or ropeway ₹150 return) rewards with panoramic views of the lake, town, and Thar Desert. Best at sunset.','location':'Ratnagiri Hill, 3km from Pushkar'},
      {'name':'Pushkar Camel Fair (November)','description':'Asia\'s largest camel fair — held on the Kartik Purnima full moon (November). 200,000+ visitors, 50,000+ camels and livestock traded. Camel races, folk performances, turban-tying contests. The sand dunes fill with colourful tents. Book accommodation 6 months ahead. 5-day event.','location':'Pushkar fair grounds (1km from town)'},
      {'name':'Rangji Temple','description':'A colorful South Indian-style Vaishnava temple (Pushkar has a large South Indian pilgrim community) with a 24m tall gopuram tower — unusual in Rajasthan. Entry: Free. Interesting contrast to the predominantly North Indian temple architecture.','location':'Central Pushkar, near bus stand'},
      {'name':'Camel, Horse & Desert Safari','description':'Pushkar is a base for exploring the Thar Desert fringes. Camel rides around the lake and to the desert dunes (₹300-500/1 hr). Overnight desert camps (15km from Pushkar, ₹2000-5000 with folk music and dinner). Horse safaris are also available through equestrian centers in town.','location':'Various operators in Pushkar town'}
    ]
  },
  'chennai': {
    'topAttractions': [
      {'name':'Marina Beach','description':'At 13km, the world\'s second longest urban beach (after Cox\'s Bazar in Bangladesh). The beach promenade (Beach Road) passes the Lighthouse, the Anna Memorial, and statues of Tamil leaders. Swimming is hazardous (strong undercurrent). Best at sunrise and sunset when thousands of Tamil families and joggers gather.','location':'South of Fort St. George, Central Chennai'},
      {'name':'Kapaleeshwarar Temple','description':'A 7th-century Dravidian Shiva temple in the Mylapore neighborhood — the spiritual heart of Chennai. The 37m gopuram (entrance tower) is encrusted with 1000+ colorful sculptures of Hindu deities. The inner tank (Kapali Theertham) reflects the tower\'s image. This is a living, active temple — arrive for the 6AM or 6PM abhishekam.','location':'Mylapore, Central Chennai'},
      {'name':'Fort St. George (1644)','description':'The first English fortress in India, built in 1644 by the British East India Company on the Coromandel Coast. Houses the Fort Museum with the oldest surviving examples of British Indian military uniform, weapons, and colonial artifacts. St. Mary\'s Church (1680, oldest surviving Anglican church in India) is inside the fort. Entry: ₹15 (Indian), ₹200 (foreign).','location':'North Chennai, on the seafront'},
      {'name':'Government Museum Chennai','description':'One of the oldest museums in India (1851, second oldest public museum in Asia). Contains the finest collection of South Indian bronzes in the world — the National Art Gallery section has 11th-15th century Chola bronzes of extraordinary quality. The Amravati collection documents 2nd century BCE Buddhist art. Entry: ₹15 (Indian), ₹250 (foreign).','location':'Egmore, Central Chennai'},
      {'name':'Mahabalipuram (Mamallapuram) Day Trip','description':'A UNESCO World Heritage Site 60km south — 7th-8th century Pallava dynasty shore temples, rathas (chariot-shaped temples), and the enormous Arjuna\'s Penance rock carving (27m × 9m bas-relief). The Shore Temple (7th century) is the oldest structural stone temple in South India. Bus from Chennai (2 hrs) or taxi.','location':'60km south of Chennai'},
      {'name':'Santhome Basilica','description':'A Roman Catholic Basilica (1896) on the Marina Beach seafront, built over the tomb of St. Thomas the Apostle (who is believed to have lived and died in Chennai/Mylapore in 72 CE). One of 3 churches in the world built over an apostle\'s tomb (the others being Rome and Spain). Open daily.','location':'Santhome, South Chennai, on Marina Beach'}
    ]
  },
  'kanyakumari': {
    'topAttractions': [
      {'name':'Kumari Amman Temple & Triveni Sangam','description':'The Kumari Amman Temple (dedicated to the goddess Kanya Devi, the virgin form of Parvati) sits at the very tip of India where three seas meet — the Triveni Sangam. Pilgrims bathe here at sunrise believing the waters wash away sins. The sunrise is unique — on certain days you can see the sun and moon on either horizon simultaneously. Non-Hindus not permitted inside the temple inner sanctum.','location':'Land\'s End, Kanyakumari'},
      {'name':'Vivekananda Rock Memorial','description':'A 1970 memorial on a small rocky island 500m offshore — reached by ferry (₹34 return, 10 min). Built where Swami Vivekananda meditated in December 1892 before traveling to Chicago for the Parliament of World\'s Religions (1893). The Memorial Hall and Dhyana Mandapam (meditation hall) are austere and beautiful. Queue for ferry can be 1-2 hrs on holidays.','location':'500m offshore from Kanyakumari beach'},
      {'name':'Thiruvalluvar Statue','description':'A 133-foot (40.5m) stone statue of the ancient Tamil poet Thiruvalluvar (1st century CE, author of Thirukkural), seated on a 38-foot pedestal representing the 38 chapters of virtue in the Thirukkural. Built in 2000, accessible by ferry from Kanyakumari beach (combined ticket with Vivekananda Rock, ₹34). The scale is monumental.','location':'On a rocky island adjacent to Vivekananda Rock'},
      {'name':'Padmanabhapuram Palace','description':'The largest wooden palace in Asia (16th century, expanded 17th-18th century), 16km from Kanyakumari in Tamil Nadu (technically in Kerala historically). Built by Travancore Rajas with intricately carved Chinese-influenced wooden ceilings, murals, and black polished granite floors. Entry: ₹25 (Indian), ₹325 (foreign). Closed Mondays.','location':'Thuckalay, 16km from Kanyakumari'},
      {'name':'Sunset View Point & Gandhi Memorial','description':'The Gandhi Memorial on the beach marks where Mahatma Gandhi\'s ashes were kept before immersion in the sea in 1948. The octagonal roof was designed so that on Gandhi\'s birthday (October 2), a sunbeam falls directly on the point where his ashes were placed. Sunset view point nearby is the best sunset location.','location':'Kanyakumari beach promenade'},
      {'name':'Wax Museum Kanyakumari','description':'A surprisingly good wax museum featuring Indian freedom fighters, scientists, sportspeople, and politicians, plus 3D shows on the geography of Kanyakumari. Entry: ₹100-200. Open 8AM-8PM. Good family attraction.','location':'Beach Road, Kanyakumari'}
    ]
  },
  'madurai': {
    'topAttractions': [
      {'name':'Meenakshi Amman Temple','description':'One of the greatest living temples in the world — a 16th-century Dravidian temple complex (2.5 acres) dedicated to Goddess Meenakshi (Parvati) and Lord Sundareshwara (Shiva). 14 gopurams (the tallest is 51.9m), over 33,000 sculptures, the Hall of 1000 Pillars, and the Golden Lotus Tank. 10,000+ devotees visit daily. The night ceremony (closing of the shrine) at 9:30PM is spectacular.','location':'Central Madurai'},
      {'name':'Thirumalai Nayakkar Mahal','description':'A 1636 Nayak-period palace built by King Thirumalai Nayakkar — only a quarter of the original palace survives, but this section (the Swargavilasam, or Heavenly Pavilion) with its massive Corinthian-style pillars (20 columns, 12m tall) and ornate stucco work is extraordinary. Sound and Light Show (6:45PM and 8PM in English and Tamil). Entry: ₹50 (Indian), ₹300 (foreign).','location':'1km from Meenakshi Temple'},
      {'name':'Gandhi Museum Madurai','description':'Housed in the Rani Mangammal Palace (17th century), the Gandhi Museum contains the blood-stained dhoti worn by Gandhi when he was assassinated on January 30, 1948 — a profoundly moving exhibit. Other galleries document the independence movement. Entry: Free. Open 10AM-1PM, 2PM-5:30PM, closed Fridays.','location':'2km from central Madurai'},
      {'name':'Azhagar Kovil Temple','description':'A 2000-year-old Vishnu temple (Kallalagar Kovil) 21km north of Madurai, set in a rocky forested hillside. The annual Chithirai Festival procession here (Pankuni Uthiram, March-April) is one of Tamil Nadu\'s most spectacular — the deity rides a golden palanquin to the Vaigai River to \'meet\' Meenakshi.','location':'21km from Madurai, Azhagarsamy Hills'},
      {'name':'Jigarthanda Street Food Trail','description':'Jigarthanda is Madurai\'s unique cold drink — a combination of milk, almond gum (badam pisin), nannari syrup, and ice cream. Invented in Madurai, sold nowhere else in authentic form. The best jigarthanda is from A. R. Jigarthanda shop (established 1942) on North Avani Moola Street near the temple. Also: Mutton Kari Dosa (meat dosa, unique to Madurai).','location':'North Avani Moola Street, near Meenakshi Temple'},
      {'name':'Vaigai Dam & Silappathikaram Trail','description':'12km from Madurai, a dam on the Vaigai River with a beautiful reservoir. Also from Madurai, the Silappathikaram — the ancient Tamil epic — is set here. The Pulimarathu Dam picnic area is popular with families on weekends.','location':'12km from central Madurai'}
    ]
  },
  'ooty': {
    'topAttractions': [
      {'name':'Nilgiri Mountain Railway (UNESCO)','description':'A UNESCO World Heritage Site — the rack-and-pinion heritage railway (1908) running 46km from Mettupalayam to Ooty through 16 tunnels and over 250 bridges, climbing from 326m to 2203m. The section from Coonoor to Ooty (20km) is the most scenic and can be traveled alone. The steam locomotive still operates on Mettupalayam-Coonoor section. Trains run 4 times daily. Book at IRCTC (₹30-300).','location':'Ooty Railway Station on Heritage Mountain Line'},
      {'name':'Botanical Gardens (Government)','description':'Established in 1848 on 22 hectares by the Marquis of Tweeddale, the Botanical Gardens contain over 1000 plant species including a 20-million-year-old fossil tree. The annual Flower Show (May) attracts 4 lakh visitors. The topiary section, the Italian Garden, and the fern house are highlights. Entry: ₹30 (Indian), ₹300 (foreign).','location':'1km from Ooty town center'},
      {'name':'Doddabetta Peak','description':'At 2637m, the highest peak in the Nilgiris and the second highest in South India (after Anamudi 2695m). The Doddabetta telescope house at the summit provides views of the surrounding tea estates, Coimbatore plains, and on exceptionally clear days, Kerala. 10km from Ooty. Entry: ₹30.','location':'10km from Ooty, on Doddabetta Road'},
      {'name':'Ooty Lake & Boating','description':'A 65-acre artificial lake built in 1824 by John Sullivan (the founder of Ooty), surrounded by eucalyptus forests. Motor and pedal boats available (₹60-100/30 min). The lakeside has the miniature train, parks, and the Boat House complex. Best on weekday mornings before crowds.','location':'Central Ooty'},
      {'name':'Pykara Lake & Falls','description':'20km from Ooty — a pristine high-altitude reservoir on the Pykara River. Motorboat rides (₹50-100), picnic meadows. The Pykara Falls (nearby) drop in two cascades through shola forest. The surrounding grasslands (shola ecosystem) are unique to the Nilgiris and host the Nilgiri Tahr (mountain goat).','location':'20km from Ooty on Mysore Road'},
      {'name':'Tea Estates & Chocolate Trail','description':'The Nilgiri tea estates produce India\'s finest CTC tea (Orthodox Nilgiri Tea). The Korakundah Estate (20km) is the world\'s highest organic tea estate (2,700m). Chocolate-making is Ooty\'s other claim to fame — visit The Chocolate House or Willy\'s Chocolate for handmade chocolates (₹200-800/box).','location':'Various estates around Ooty and Coonoor'}
    ]
  },
  'hyderabad': {
    'topAttractions': [
      {'name':'Charminar (Four Towers)','description':'The symbol of Hyderabad — a 1591 CE mosque-cum-monument built by Muhammad Quli Qutb Shah to commemorate the end of a plague. Four 56m minarets, an upper-floor mosque, and 149 steps to the top for views over Old Hyderabad. Entry: ₹25 (Indian), ₹300 (foreign). Open 9:30AM-5:30PM. The Laad Bazaar (bangle market) adjacent is spectacular.','location':'Central Old Hyderabad, Charminar junction'},
      {'name':'Golconda Fort','description':'A 16th-century diamond-trade fortress (1518-1687) that housed the Koh-i-Noor and Hope Diamond before they were taken away. The acoustic system is extraordinary — a hand-clap at the entrance gate is heard 1km away at the top. Sound and Light Show (7PM English, 8PM Hindi). The "Bala Hisar" (upper fort) gives panoramic views. Entry: ₹35 (Indian), ₹500 (foreign).','location':'8km west of Charminar'},
      {'name':'Ramoji Film City','description':'The world\'s largest integrated film studio complex (Guinness World Records, 1666 acres), 30km from Hyderabad. Tours show active and inactive film sets, working studios, theme park areas. 50+ films shoot simultaneously. Day tour package: ₹1200-2000. Accommodation on-site (₹3000-8000/night).','location':'30km from Hyderabad, on the Vijayawada highway'},
      {'name':'Salar Jung Museum','description':'The world\'s largest single-person collection — Nawab Mir Yousuf Ali Khan (Salar Jung III) spent 35+ years and his entire fortune collecting 35,000 objects from 35 countries: Mughal paintings, Japanese netsuke, European statues, ancient weapons, manuscripts. Entry: ₹20 (Indian), ₹500 (foreign). Open 10AM-5PM, closed Fridays.','location':'Dar-ul-Shifa, Old Hyderabad'},
      {'name':'Hussain Sagar Lake & Buddha Statue','description':'A 16km-perimeter artificial lake (1563 CE) connecting old Hyderabad and Secunderabad. In the center stands a 17.5m monolithic Buddha statue (installed 1992 after 3 sinking attempts — still bears the ropes used for the 4th attempt). Boat rides to the statue (₹60 return) from Lumbini Park and Tank Bund.','location':'Central Hyderabad, between old and new cities'},
      {'name':'Old Hyderabad Food Trail (Biryani)','description':'Hyderabad\'s Dum Biryani is a serious culinary culture — slow-cooked basmati rice and meat in a sealed pot. Paradise Restaurant (est 1953) and Bawarchi (est 1967) serve the most famous versions (₹250-450). Haleem (slow-cooked wheat-meat stew, best during Ramadan) and the Irani Chai + Osmania Biscuit combination are essential.','location':'Paradise Restaurant: Secunderabad; Bawarchi: Himayatnagar'}
    ]
  },
  'pune': {
    'topAttractions': [
      {'name': 'Aga Khan Palace', 'description': 'Built in 1892, this majestic palace served as a prison for Mahatma Gandhi and his wife Kasturba Gandhi during the 1942 Quit India Movement. Kasturba died here, and her samadhi is in the palace grounds. It\'s now a museum of Gandhi\'s life. Entry: ₹25.', 'location': 'Kalyani Nagar, Pune'},
      {'name': 'Shaniwar Wada', 'description': 'The historic 1732 fortification that served as the seat of the Peshwas of the Maratha Empire until 1818. Largely destroyed by an unexplained fire in 1828, the imposing walls, gateways (Dilli Darwaza), and foundations remain. Evening sound and light show. Entry: ₹25.', 'location': 'Shaniwar Peth, Old Pune'},
      {'name': 'Dagadusheth Halwai Ganapati Temple', 'description': 'One of the most famous Hindu temples in Maharashtra, dedicated to Lord Ganesha. The idol is adorned with nearly 40 kilos of gold. During the 10-day Ganeshotsav festival, millions of devotees visit. It remains open from 6 AM to 11 PM.', 'location': 'Budhwar Peth, Old Pune'},
      {'name': 'Osho International Meditation Resort', 'description': 'A sprawling, lush ashram in Koregaon Park founded by the controversial mystic Rajneesh (Osho). Attracts thousands of international visitors for its meditation programs. The environment is serene with black marble paths and greenery. Entry is restricted (day passes available for ₹1000-2000).', 'location': 'Koregaon Park, Pune'},
      {'name': 'Sinhagad Fort', 'description': 'A massive 17th-century hill fort located 30km from Pune at an elevation of 1312m. Famous for the 1670 Battle of Sinhagad fought by Tanaji Malusare. A popular trekking destination offering spectacular views of the Sahyadri mountains and Khadakwasla Dam. The hike takes about 1-2 hours from the base.', 'location': '30km from Pune'},
      {'name': 'Raja Dinkar Kelkar Museum', 'description': 'A fascinating one-man collection by Dr. Dinkar Kelkar, housing over 20,000 artifacts from 18th and 19th-century India. Includes musical instruments, hookahs, writing instruments, and a replica of the Mastani Mahal. Entry: ₹100.', 'location': 'Shukrawar Peth, Pune'}
    ]
  },
  'bikaner': { // Already covered, but just to be sure
    'topAttractions': [
      {'name':'Junagarh Fort','description':'One of the finest forts in Rajasthan (1593 CE, built by Raja Rai Singh), never conquered despite multiple attacks. 37 palaces, temples, and pavilions inside the 5.28-acre complex — Anup Mahal (red sandstone with gold filigree), Phool Mahal, Badal Mahal, and the Karan Mahal. The Indian Air Force museum section has a vintage WWII biplane. Entry: ₹100 (Indian), ₹500 (foreign).','location':'Central Bikaner'},
      {'name':'Karni Mata Temple (Rat Temple)','description':'A revered temple 30km south at Deshnok dedicated to Karni Mata (a 15th-century mystic). Over 25,000 rats (kabas) live here and are considered sacred — believed to be reincarnated devotees awaiting rebirth as humans. White rats are especially auspicious. Pilgrims walk barefoot on rat-infested floors. Entry: ₹10 (Indian), ₹50 (foreign, without camera).','location':'Deshnok, 30km from Bikaner'},
      {'name':'Lalgarh Palace','description':'A magnificent Indo-Saracenic palace complex built by Maharaja Ganga Singh in 1902 using local pink sandstone and Belgian glass. Now partly a heritage hotel (Laxmi Niwas Hotel), partly the Sadul Museum with royal portraits, hunting trophies, and vintage photographs.','location':'Northern Bikaner'},
      {'name':'National Research Centre on Camel','description':'India\'s only camel research center, 8km from Bikaner — home to 300+ camels of different breeds including the Bikaneri breed (best for carrying loads). Camel rides, camel milk tasting (₹30/glass, claimed to have medicinal properties). A unique and educational visit.','location':'8km from Bikaner, Jorbeer'},
      {'name':'Bikaneri Bhujia & Food Trail','description':'Bikaner is the birthplace of Bhujia namkeen — crispy spiced moth bean noodles that became a national snack. Original Haldiram\'s started here. The Kote Gate area has dozens of competing bhujia manufacturers. Visit the old city bhujia markets and buy directly from traditional makers (₹150-500/kg, far better than packaged).','location':'Kote Gate area, old city'},
      {'name':'Gajner Palace & Gajner Wildlife Sanctuary','description':'A 32km drive from Bikaner brings you to this former Maharaja of Bikaner hunting lodge (1884) on the shores of Gajner Lake — now a heritage hotel. The Gajner Wildlife Sanctuary has blackbuck, chinkara, and wild boar. The lake attracts imperial sandgrouse (thousands in winter) and flamingos.','location':'32km from Bikaner on NH15'}
    ]
  }
};

function readAllFiles(dir, filelist = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filepath = path.join(dir, file);
    if (fs.statSync(filepath).isDirectory()) {
      filelist = readAllFiles(filepath, filelist);
    } else if (file.endsWith('.json')) {
      filelist.push(filepath);
    }
  }
  return filelist;
}

const files = readAllFiles(baseDir);
let patched = 0;

for (const file of files) {
  try {
    const content = fs.readFileSync(file, 'utf-8');
    const data = JSON.parse(content);
    const slug = data.slug;
    if (PATCHES[slug]) {
      for (const [key, val] of Object.entries(PATCHES[slug])) {
        data[key] = val;
      }
      fs.writeFileSync(file, JSON.stringify(data, null, 2));
      console.log('  ✅ Patched ' + key + ' for ' + data.name);
      patched++;
    }
  } catch (e) {
    // console.log('Skipping ' + file, e.message);
  }
}
console.log('Total files patched: ' + patched);
