import apiClient, { ApiResponse } from './apiClient';

export interface DestinationInfo {
  name: string;
  country: string;
  countryCode: string;
  category: string;
  lat: number;
  lng: number;
  weather: string;
  season: string;
  description: string;
  emoji?: string;
}

export interface SearchedDestination {
  name: string;
  country?: string;
  latitude: number;
  longitude: number;
  placeId?: string;
  formattedAddress: string;
}

export const exploreService = {
  getFeaturedDestinations: async (): Promise<ApiResponse<any>> => {
    // Fetch from static JSON generated by data pipeline
    try {
      const res = await fetch('/data/destinations/destinations-index.json');
      const data = await res.json();
      return { success: true, data, message: 'OK' };
    } catch (e) {
      return { success: false, data: [], message: 'Failed to load destinations' };
    }
  },

  searchDestinations: async (query: string): Promise<ApiResponse<SearchedDestination[]>> => {
    return apiClient.get(`/explore/search?q=${encodeURIComponent(query)}`);
  },
};
