import { Destination } from '../../types';

const europeDestinations: any[] = [
  {
    name: "Paris",
    country: "France",
    state: "Île-de-France",
    latitude: 48.8566,
    longitude: 2.3522,
    description: "The City of Light, world-renowned for art, fashion, and romance.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Eiffel Tower",
        type: "ATTRACTION",
        latitude: 48.8584,
        longitude: 2.2945,
        description: "Iconic iron lattice tower.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Louvre Museum",
        type: "ATTRACTION",
        latitude: 48.8606,
        longitude: 2.3376,
        description: "World's largest art museum.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Notre-Dame Cathedral",
        type: "ATTRACTION",
        latitude: 48.8529,
        longitude: 2.3499,
        description: "Historic Catholic cathedral.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Arc de Triomphe",
        type: "ATTRACTION",
        latitude: 48.8738,
        longitude: 2.295,
        description: "Monument honoring those who fought for France.",
        activityCategories: ["Monument"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Sacré-Cœur",
        type: "ATTRACTION",
        latitude: 48.8867,
        longitude: 2.3431,
        description: "Roman Catholic church dedicated to the Sacred Heart.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Rome",
    country: "Italy",
    state: "Lazio",
    latitude: 41.9028,
    longitude: 12.4964,
    description: "The Eternal City, featuring 3,000 years of globally influential art and architecture.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Colosseum",
        type: "ATTRACTION",
        latitude: 41.8902,
        longitude: 12.4922,
        description: "Ancient gladiatorial arena.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Trevi Fountain",
        type: "ATTRACTION",
        latitude: 41.9009,
        longitude: 12.4833,
        description: "Elaborate 18th-century fountain.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Pantheon",
        type: "ATTRACTION",
        latitude: 41.8986,
        longitude: 12.4769,
        description: "Former Roman temple, now a church.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Roman Forum",
        type: "ATTRACTION",
        latitude: 41.8925,
        longitude: 12.4853,
        description: "Ruins of ancient government buildings.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Vatican Museums",
        type: "ATTRACTION",
        latitude: 41.9065,
        longitude: 12.4536,
        description: "Extensive collections of art in Vatican City.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "London",
    country: "United Kingdom",
    state: "England",
    latitude: 51.5074,
    longitude: -0.1278,
    description: "A vibrant 21st-century city with a history stretching back to Roman times.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Big Ben",
        type: "ATTRACTION",
        latitude: 51.5007,
        longitude: -0.1246,
        description: "Massive iconic clock tower.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Tower of London",
        type: "ATTRACTION",
        latitude: 51.5081,
        longitude: -0.0759,
        description: "Historic castle and prison.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$35",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "British Museum",
        type: "ATTRACTION",
        latitude: 51.5194,
        longitude: -0.127,
        description: "Vast collection of world art and artifacts.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "London Eye",
        type: "ATTRACTION",
        latitude: 51.5033,
        longitude: -0.1195,
        description: "Enormous observation wheel on the Thames.",
        activityCategories: ["Attraction"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$40",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Buckingham Palace",
        type: "ATTRACTION",
        latitude: 51.5014,
        longitude: -0.1419,
        description: "The London residence of the monarch.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$40",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Barcelona",
    country: "Spain",
    state: "Catalonia",
    latitude: 41.3851,
    longitude: 2.1734,
    description: "A cosmopolitan capital famous for Antoni Gaudí's modernist architecture.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Sagrada Familia",
        type: "ATTRACTION",
        latitude: 41.4036,
        longitude: 2.1744,
        description: "Gaudí's unfinished basilica.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Park Güell",
        type: "ATTRACTION",
        latitude: 41.4145,
        longitude: 2.1527,
        description: "Mosaic-filled public park designed by Gaudí.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Casa Batlló",
        type: "ATTRACTION",
        latitude: 41.3916,
        longitude: 2.1649,
        description: "Modernist building by Antoni Gaudí.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$35",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Gothic Quarter",
        type: "ATTRACTION",
        latitude: 41.3827,
        longitude: 2.177,
        description: "Historic center with narrow medieval streets.",
        activityCategories: ["Neighborhood"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "La Rambla",
        type: "ATTRACTION",
        latitude: 41.381,
        longitude: 2.1734,
        description: "Famous tree-lined pedestrian street.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Berlin",
    country: "Germany",
    state: "Berlin",
    latitude: 52.52,
    longitude: 13.405,
    description: "Germany's capital known for its art scene, modern landmarks, and history.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Brandenburg Gate",
        type: "ATTRACTION",
        latitude: 52.5163,
        longitude: 13.3777,
        description: "18th-century neoclassical monument.",
        activityCategories: ["Monument"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Reichstag Building",
        type: "ATTRACTION",
        latitude: 52.5186,
        longitude: 13.3763,
        description: "Historic parliament building with a glass dome.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Berlin Wall Memorial",
        type: "ATTRACTION",
        latitude: 52.535,
        longitude: 13.39,
        description: "Memorial site of the divided city.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Museum Island",
        type: "ATTRACTION",
        latitude: 52.5169,
        longitude: 13.401,
        description: "Island complex housing five major museums.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Berlin TV Tower",
        type: "ATTRACTION",
        latitude: 52.5208,
        longitude: 13.4094,
        description: "Iconic tower with observation deck.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$28",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    state: "North Holland",
    latitude: 52.3676,
    longitude: 4.9041,
    description: "Capital known for its artistic heritage, elaborate canal system, and narrow houses.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Rijksmuseum",
        type: "ATTRACTION",
        latitude: 52.36,
        longitude: 4.8852,
        description: "Dutch national museum of arts and history.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Van Gogh Museum",
        type: "ATTRACTION",
        latitude: 52.3581,
        longitude: 4.8812,
        description: "Museum dedicated to Vincent van Gogh.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$22",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Anne Frank House",
        type: "ATTRACTION",
        latitude: 52.3752,
        longitude: 4.8839,
        description: "Biographical museum of Anne Frank.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Vondelpark",
        type: "ATTRACTION",
        latitude: 52.358,
        longitude: 4.8686,
        description: "Famous public urban park.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Dam Square",
        type: "ATTRACTION",
        latitude: 52.3729,
        longitude: 4.893,
        description: "City square lined with notable buildings.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Prague",
    country: "Czech Republic",
    state: "Prague",
    latitude: 50.0755,
    longitude: 14.4378,
    description: "The City of a Hundred Spires, known for its Old Town Square and baroque buildings.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Charles Bridge",
        type: "ATTRACTION",
        latitude: 50.0865,
        longitude: 14.4114,
        description: "Historic bridge crossing the Vltava river.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Prague Castle",
        type: "ATTRACTION",
        latitude: 50.0903,
        longitude: 14.3996,
        description: "Vast castle complex with various architectural styles.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Old Town Square",
        type: "ATTRACTION",
        latitude: 50.0875,
        longitude: 14.4213,
        description: "Historic square in the Old Town quarter.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Prague Astronomical Clock",
        type: "ATTRACTION",
        latitude: 50.087,
        longitude: 14.4207,
        description: "Medieval astronomical clock.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$12",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Wenceslas Square",
        type: "ATTRACTION",
        latitude: 50.0811,
        longitude: 14.4267,
        description: "Main city square and center of business.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Vienna",
    country: "Austria",
    state: "Vienna",
    latitude: 48.2082,
    longitude: 16.3738,
    description: "Austria’s capital lies in the country’s east on the Danube River, known for Imperial palaces.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Schönbrunn Palace",
        type: "ATTRACTION",
        latitude: 48.1849,
        longitude: 16.3122,
        description: "Former imperial summer residence.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$28",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Hofburg",
        type: "ATTRACTION",
        latitude: 48.2065,
        longitude: 16.3653,
        description: "Former principal imperial palace.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$22",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Belvedere Palace",
        type: "ATTRACTION",
        latitude: 48.1915,
        longitude: 16.3807,
        description: "Historic building complex in Vienna.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "St. Stephen's Cathedral",
        type: "ATTRACTION",
        latitude: 48.2085,
        longitude: 16.3731,
        description: "Mother church of the Roman Catholic Archdiocese.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Vienna State Opera",
        type: "ATTRACTION",
        latitude: 48.203,
        longitude: 16.3691,
        description: "One of the world's leading opera houses.",
        activityCategories: ["Theatre"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Florence",
    country: "Italy",
    state: "Tuscany",
    latitude: 43.7695,
    longitude: 11.2558,
    description: "Capital of Italy’s Tuscany region, home to many masterpieces of Renaissance art.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Duomo di Firenze",
        type: "ATTRACTION",
        latitude: 43.7731,
        longitude: 11.256,
        description: "Iconic cathedral with a terracotta-tiled dome.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Uffizi Gallery",
        type: "ATTRACTION",
        latitude: 43.7677,
        longitude: 11.2553,
        description: "Prominent art museum.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Ponte Vecchio",
        type: "ATTRACTION",
        latitude: 43.768,
        longitude: 11.2531,
        description: "Medieval stone closed-spandrel segmental arch bridge.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Galleria dell'Accademia",
        type: "ATTRACTION",
        latitude: 43.7769,
        longitude: 11.2587,
        description: "Home to Michelangelo's sculpture David.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Palazzo Vecchio",
        type: "ATTRACTION",
        latitude: 43.7693,
        longitude: 11.2561,
        description: "Town hall of Florence.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Venice",
    country: "Italy",
    state: "Veneto",
    latitude: 45.4408,
    longitude: 12.3155,
    description: "Built on more than 100 small islands in a lagoon in the Adriatic Sea.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "luxury",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "St. Mark's Basilica",
        type: "ATTRACTION",
        latitude: 45.4346,
        longitude: 12.3396,
        description: "Cathedral church of the Roman Catholic Patriarchate.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Doge's Palace",
        type: "ATTRACTION",
        latitude: 45.4337,
        longitude: 12.3404,
        description: "Palace built in Venetian Gothic style.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$35",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Rialto Bridge",
        type: "ATTRACTION",
        latitude: 45.438,
        longitude: 12.3359,
        description: "Oldest of the four bridges spanning the Grand Canal.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Grand Canal",
        type: "ATTRACTION",
        latitude: 45.4384,
        longitude: 12.3323,
        description: "Major water-traffic corridor in the city.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Bridge of Sighs",
        type: "ATTRACTION",
        latitude: 45.434,
        longitude: 12.3408,
        description: "Enclosed bridge made of white limestone.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Madrid",
    country: "Spain",
    state: "Community of Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
    description: "Central capital known for elegant boulevards and expansive, manicured parks.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Prado Museum",
        type: "ATTRACTION",
        latitude: 40.4138,
        longitude: -3.6921,
        description: "Main Spanish national art museum.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Royal Palace of Madrid",
        type: "ATTRACTION",
        latitude: 40.418,
        longitude: -3.7143,
        description: "Official residence of the Spanish royal family.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Retiro Park",
        type: "ATTRACTION",
        latitude: 40.4153,
        longitude: -3.6845,
        description: "One of the largest parks in the city.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Plaza Mayor",
        type: "ATTRACTION",
        latitude: 40.4155,
        longitude: -3.7074,
        description: "Major public space in the heart of Madrid.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Puerta del Sol",
        type: "ATTRACTION",
        latitude: 40.4169,
        longitude: -3.7036,
        description: "Public square and one of the best known and busiest places in Madrid.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Munich",
    country: "Germany",
    state: "Bavaria",
    latitude: 48.1351,
    longitude: 11.582,
    description: "Bavarian capital known for its annual Oktoberfest celebration and beer halls.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Marienplatz",
        type: "ATTRACTION",
        latitude: 48.1371,
        longitude: 11.5754,
        description: "Central square in the city centre.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Nymphenburg Palace",
        type: "ATTRACTION",
        latitude: 48.1581,
        longitude: 11.5034,
        description: "Baroque palace in the western part of Munich.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "English Garden",
        type: "ATTRACTION",
        latitude: 48.1527,
        longitude: 11.5966,
        description: "Large public park in the centre of Munich.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Deutsches Museum",
        type: "ATTRACTION",
        latitude: 48.1301,
        longitude: 11.5833,
        description: "World's largest museum of science and technology.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Hofbräuhaus",
        type: "ATTRACTION",
        latitude: 48.1376,
        longitude: 11.58,
        description: "Famous beer hall in Munich.",
        activityCategories: ["Restaurant"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Varies",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Budapest",
    country: "Hungary",
    state: "Central Hungary",
    latitude: 47.4979,
    longitude: 19.0402,
    description: "Hungary’s capital, bisected by the River Danube, known for thermal baths.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "low",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Hungarian Parliament Building",
        type: "ATTRACTION",
        latitude: 47.5071,
        longitude: 19.0456,
        description: "Seat of the National Assembly of Hungary.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Buda Castle",
        type: "ATTRACTION",
        latitude: 47.4962,
        longitude: 19.0396,
        description: "Historical castle and palace complex.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Fisherman's Bastion",
        type: "ATTRACTION",
        latitude: 47.5022,
        longitude: 19.0347,
        description: "Monument with panoramic views of the city.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Széchenyi Thermal Bath",
        type: "ATTRACTION",
        latitude: 47.5186,
        longitude: 19.0823,
        description: "Largest medicinal bath in Europe.",
        activityCategories: ["Attraction"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "St. Stephen's Basilica",
        type: "ATTRACTION",
        latitude: 47.5009,
        longitude: 19.0539,
        description: "Roman Catholic basilica.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Lisbon",
    country: "Portugal",
    state: "Lisbon",
    latitude: 38.7223,
    longitude: -9.1393,
    description: "Hilly, coastal capital city known for its cafe culture and fado music.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Belém Tower",
        type: "ATTRACTION",
        latitude: 38.6916,
        longitude: -9.2159,
        description: "16th-century fortification.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Jerónimos Monastery",
        type: "ATTRACTION",
        latitude: 38.6979,
        longitude: -9.2067,
        description: "Former monastery of the Order of Saint Jerome.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$12",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Castelo de S. Jorge",
        type: "ATTRACTION",
        latitude: 38.7139,
        longitude: -9.1334,
        description: "Historic castle overlooking the city.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Praça do Comércio",
        type: "ATTRACTION",
        latitude: 38.7075,
        longitude: -9.1364,
        description: "Large harbor-facing plaza.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Alfama",
        type: "ATTRACTION",
        latitude: 38.7126,
        longitude: -9.1306,
        description: "Oldest district of Lisbon.",
        activityCategories: ["Neighborhood"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Dublin",
    country: "Ireland",
    state: "Leinster",
    latitude: 53.3498,
    longitude: -6.2603,
    description: "Capital of the Republic of Ireland, situated at the mouth of the River Liffey.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Guinness Storehouse",
        type: "ATTRACTION",
        latitude: 53.3419,
        longitude: -6.2867,
        description: "Brewery experience telling the tale of Ireland's famous beer.",
        activityCategories: ["Attraction"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Trinity College Library",
        type: "ATTRACTION",
        latitude: 53.3438,
        longitude: -6.2546,
        description: "Historic library housing the Book of Kells.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "St Patrick's Cathedral",
        type: "ATTRACTION",
        latitude: 53.3395,
        longitude: -6.2714,
        description: "National cathedral of the Church of Ireland.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Kilmainham Gaol",
        type: "ATTRACTION",
        latitude: 53.3418,
        longitude: -6.3098,
        description: "Former prison, now a museum.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Temple Bar",
        type: "ATTRACTION",
        latitude: 53.3454,
        longitude: -6.2642,
        description: "Busy riverside neighbourhood known for pubs.",
        activityCategories: ["Neighborhood"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Edinburgh",
    country: "United Kingdom",
    state: "Scotland",
    latitude: 55.9533,
    longitude: -3.1883,
    description: "Scotland's compact, hilly capital with a medieval Old Town and elegant Georgian New Town.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Edinburgh Castle",
        type: "ATTRACTION",
        latitude: 55.9486,
        longitude: -3.2008,
        description: "Historic fortress dominating the skyline.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Royal Mile",
        type: "ATTRACTION",
        latitude: 55.9495,
        longitude: -3.1909,
        description: "Succession of streets forming the main thoroughfare.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Palace of Holyroodhouse",
        type: "ATTRACTION",
        latitude: 55.9527,
        longitude: -3.1722,
        description: "Official residence of the British monarch in Scotland.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$22",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Arthur's Seat",
        type: "ATTRACTION",
        latitude: 55.9441,
        longitude: -3.1618,
        description: "Ancient volcano and main peak of the group of hills in Edinburgh.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "National Museum of Scotland",
        type: "ATTRACTION",
        latitude: 55.9472,
        longitude: -3.1899,
        description: "Museum exploring natural world, cultures, and Scottish history.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Athens",
    country: "Greece",
    state: "Attica",
    latitude: 37.9838,
    longitude: 23.7275,
    description: "Historical capital of Europe with iconic ruins from ancient Greece.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Acropolis of Athens",
        type: "ATTRACTION",
        latitude: 37.9715,
        longitude: 23.7262,
        description: "Ancient citadel containing remains of significant buildings.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Parthenon",
        type: "ATTRACTION",
        latitude: 37.9715,
        longitude: 23.7267,
        description: "Former temple dedicated to the goddess Athena.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Included in Acropolis",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Acropolis Museum",
        type: "ATTRACTION",
        latitude: 37.9685,
        longitude: 23.7285,
        description: "Archaeological museum focused on the Acropolis findings.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Ancient Agora",
        type: "ATTRACTION",
        latitude: 37.975,
        longitude: 23.7225,
        description: "Best-known example of an ancient Greek agora.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$12",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Temple of Olympian Zeus",
        type: "ATTRACTION",
        latitude: 37.9693,
        longitude: 23.7331,
        description: "Former colossal temple at the center of the city.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Istanbul",
    country: "Turkey",
    state: "Istanbul",
    latitude: 41.0082,
    longitude: 28.9784,
    description: "A major city straddling Europe and Asia across the Bosphorus Strait.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "low",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Hagia Sophia",
        type: "ATTRACTION",
        latitude: 41.0086,
        longitude: 28.9802,
        description: "Late antique place of worship in Istanbul.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Blue Mosque",
        type: "ATTRACTION",
        latitude: 41.0054,
        longitude: 28.9768,
        description: "Historic mosque known for its blue tiles.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Topkapi Palace",
        type: "ATTRACTION",
        latitude: 41.0115,
        longitude: 28.9833,
        description: "Vast museum and former residence of Ottoman sultans.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Grand Bazaar",
        type: "ATTRACTION",
        latitude: 41.0108,
        longitude: 28.968,
        description: "One of the largest and oldest covered markets.",
        activityCategories: ["Attraction"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Basilica Cistern",
        type: "ATTRACTION",
        latitude: 41.0084,
        longitude: 28.9779,
        description: "Largest of several hundred ancient cisterns.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Copenhagen",
    country: "Denmark",
    state: "Capital Region",
    latitude: 55.6761,
    longitude: 12.5683,
    description: "Denmark's capital sitting on the coastal islands of Zealand and Amager.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Tivoli Gardens",
        type: "ATTRACTION",
        latitude: 55.6737,
        longitude: 12.5681,
        description: "Historic amusement park and pleasure garden.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$22",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "The Little Mermaid",
        type: "ATTRACTION",
        latitude: 55.6929,
        longitude: 12.5993,
        description: "Bronze statue by Edvard Eriksen.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Nyhavn",
        type: "ATTRACTION",
        latitude: 55.68,
        longitude: 12.59,
        description: "17th-century waterfront, canal and entertainment district.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Amalienborg",
        type: "ATTRACTION",
        latitude: 55.6841,
        longitude: 12.5933,
        description: "Home of the Danish royal family.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Rosenborg Castle",
        type: "ATTRACTION",
        latitude: 55.6848,
        longitude: 12.5765,
        description: "Renaissance castle housing crown jewels.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Stockholm",
    country: "Sweden",
    state: "Stockholm County",
    latitude: 59.3293,
    longitude: 18.0686,
    description: "Capital of Sweden, encompassing 14 islands and more than 50 bridges.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Vasa Museum",
        type: "ATTRACTION",
        latitude: 59.328,
        longitude: 18.0914,
        description: "Maritime museum displaying a 17th-century ship.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Skansen",
        type: "ATTRACTION",
        latitude: 59.327,
        longitude: 18.1037,
        description: "Oldest open-air museum and zoo in Sweden.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$22",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Stockholm Palace",
        type: "ATTRACTION",
        latitude: 59.3268,
        longitude: 18.0717,
        description: "Official residence of the Swedish monarch.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Gamla Stan",
        type: "ATTRACTION",
        latitude: 59.3256,
        longitude: 18.0719,
        description: "The old town of Stockholm.",
        activityCategories: ["Neighborhood"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "ABBA The Museum",
        type: "ATTRACTION",
        latitude: 59.3248,
        longitude: 18.0965,
        description: "Interactive exhibition about the pop band ABBA.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Oslo",
    country: "Norway",
    state: "Oslo",
    latitude: 59.9139,
    longitude: 10.7522,
    description: "Capital city of Norway, known for its green spaces and museums.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "luxury",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Viking Ship Museum",
        type: "ATTRACTION",
        latitude: 59.9049,
        longitude: 10.6844,
        description: "Museum housing preserved Viking ships.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Vigeland Sculpture Park",
        type: "ATTRACTION",
        latitude: 59.927,
        longitude: 10.7,
        description: "Park containing sculptures by Gustav Vigeland.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Oslo Opera House",
        type: "ATTRACTION",
        latitude: 59.9075,
        longitude: 10.7531,
        description: "Home of the Norwegian National Opera.",
        activityCategories: ["Theatre"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Akershus Fortress",
        type: "ATTRACTION",
        latitude: 59.9076,
        longitude: 10.7371,
        description: "Medieval castle built to protect Oslo.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Fram Museum",
        type: "ATTRACTION",
        latitude: 59.903,
        longitude: 10.6996,
        description: "Museum telling the story of Norwegian polar exploration.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Helsinki",
    country: "Finland",
    state: "Uusimaa",
    latitude: 60.1695,
    longitude: 24.9354,
    description: "Finland's southern capital, known for sea-facing landscape and diverse architecture.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "high",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Suomenlinna",
        type: "ATTRACTION",
        latitude: 60.1454,
        longitude: 24.9866,
        description: "18th-century sea fortress and nature area.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Helsinki Cathedral",
        type: "ATTRACTION",
        latitude: 60.1702,
        longitude: 24.9522,
        description: "Evangelical Lutheran cathedral.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Temppeliaukio Church",
        type: "ATTRACTION",
        latitude: 60.173,
        longitude: 24.9252,
        description: "Lutheran church built directly into solid rock.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Uspenski Cathedral",
        type: "ATTRACTION",
        latitude: 60.1683,
        longitude: 24.961,
        description: "Eastern Orthodox cathedral in Helsinki.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Market Square",
        type: "ATTRACTION",
        latitude: 60.1675,
        longitude: 24.9537,
        description: "Central square known for food and souvenirs.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Warsaw",
    country: "Poland",
    state: "Masovian Voivodeship",
    latitude: 52.2297,
    longitude: 21.0122,
    description: "Poland's capital offering a blend of modern architecture and restored historical buildings.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "low",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Warsaw Old Town",
        type: "ATTRACTION",
        latitude: 52.2497,
        longitude: 21.0122,
        description: "Historic center rebuilt after WWII.",
        activityCategories: ["Neighborhood"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Royal Castle",
        type: "ATTRACTION",
        latitude: 52.248,
        longitude: 21.015,
        description: "State rooms and art exhibits in a reconstructed castle.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Lazienki Park",
        type: "ATTRACTION",
        latitude: 52.215,
        longitude: 21.0333,
        description: "The largest park in Warsaw.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Palace of Culture and Science",
        type: "ATTRACTION",
        latitude: 52.2319,
        longitude: 21.0067,
        description: "High-rise building known for its distinctive architecture.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$8",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Warsaw Uprising Museum",
        type: "ATTRACTION",
        latitude: 52.2323,
        longitude: 20.981,
        description: "Museum dedicated to the Warsaw Uprising of 1944.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Krakow",
    country: "Poland",
    state: "Lesser Poland",
    latitude: 50.0647,
    longitude: 19.945,
    description: "A southern Poland city known for its well-preserved medieval core.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "low",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Wawel Royal Castle",
        type: "ATTRACTION",
        latitude: 50.0541,
        longitude: 19.9354,
        description: "Castle residency on Wawel Hill.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$12",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Main Square",
        type: "ATTRACTION",
        latitude: 50.0614,
        longitude: 19.9372,
        description: "Vast medieval market square.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "St. Mary's Basilica",
        type: "ATTRACTION",
        latitude: 50.0616,
        longitude: 19.9393,
        description: "Brick Gothic church adjacent to the Main Square.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Kraków Cloth Hall",
        type: "ATTRACTION",
        latitude: 50.0615,
        longitude: 19.9373,
        description: "Renaissance market building in the Main Square.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Oskar Schindler's Enamel Factory",
        type: "ATTRACTION",
        latitude: 50.0474,
        longitude: 19.9616,
        description: "Museum about the Nazi occupation of Kraków.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Milan",
    country: "Italy",
    state: "Lombardy",
    latitude: 45.4642,
    longitude: 9.19,
    description: "A global capital of fashion and design in northern Italy.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "luxury",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Milan Cathedral (Duomo)",
        type: "ATTRACTION",
        latitude: 45.4641,
        longitude: 9.1919,
        description: "Magnificent Gothic cathedral.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Galleria Vittorio Emanuele II",
        type: "ATTRACTION",
        latitude: 45.4659,
        longitude: 9.1899,
        description: "Italy's oldest active shopping mall.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Sforzesco Castle",
        type: "ATTRACTION",
        latitude: 45.4705,
        longitude: 9.1793,
        description: "15th-century castle housing art collections.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$10",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Santa Maria delle Grazie",
        type: "ATTRACTION",
        latitude: 45.4659,
        longitude: 9.1709,
        description: "Church housing Da Vinci's The Last Supper.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Teatro alla Scala",
        type: "ATTRACTION",
        latitude: 45.4674,
        longitude: 9.1895,
        description: "Historic and prestigious opera house.",
        activityCategories: ["Theatre"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$30",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Naples",
    country: "Italy",
    state: "Campania",
    latitude: 40.8518,
    longitude: 14.2681,
    description: "A major city in southern Italy known for its art, architecture, and food.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Pompeii Archaeological Park",
        type: "ATTRACTION",
        latitude: 40.749,
        longitude: 14.4862,
        description: "Ruins of the ancient Roman city.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$22",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Mount Vesuvius",
        type: "ATTRACTION",
        latitude: 40.8224,
        longitude: 14.4289,
        description: "Somma-stratovolcano overlooking the Bay of Naples.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Naples National Archaeological Museum",
        type: "ATTRACTION",
        latitude: 40.8534,
        longitude: 14.2505,
        description: "Museum housing Roman artifacts.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Castel dell'Ovo",
        type: "ATTRACTION",
        latitude: 40.8282,
        longitude: 14.2483,
        description: "Seaside castle on a former island.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Royal Palace of Naples",
        type: "ATTRACTION",
        latitude: 40.8364,
        longitude: 14.2496,
        description: "Palace built for the Bourbon Kings.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$12",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Seville",
    country: "Spain",
    state: "Andalusia",
    latitude: 37.3891,
    longitude: -5.9845,
    description: "Capital of the Andalusia region, famous for flamenco dancing and architectural design.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Spring",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Plaza de España",
        type: "ATTRACTION",
        latitude: 37.3772,
        longitude: -5.9869,
        description: "Landmark square featuring beautiful tiles and canals.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Royal Alcázar of Seville",
        type: "ATTRACTION",
        latitude: 37.3831,
        longitude: -5.9902,
        description: "Moorish renaissance royal palace.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Seville Cathedral",
        type: "ATTRACTION",
        latitude: 37.3861,
        longitude: -5.9926,
        description: "Massive Gothic cathedral and Columbus's tomb.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Giralda",
        type: "ATTRACTION",
        latitude: 37.3862,
        longitude: -5.9925,
        description: "The bell tower of Seville Cathedral.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Included in Cathedral",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Torre del Oro",
        type: "ATTRACTION",
        latitude: 37.3824,
        longitude: -5.9963,
        description: "Dodecagonal military watchtower.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Porto",
    country: "Portugal",
    state: "Porto District",
    latitude: 41.1579,
    longitude: -8.6291,
    description: "Coastal city in northwest Portugal known for its stately bridges and port wine.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Autumn",
    averageBudget: "medium",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Dom Luís I Bridge",
        type: "ATTRACTION",
        latitude: 41.14,
        longitude: -8.6095,
        description: "Double-deck metal arch bridge.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Livraria Lello",
        type: "ATTRACTION",
        latitude: 41.1468,
        longitude: -8.6147,
        description: "Historic, ornate bookstore.",
        activityCategories: ["Attraction"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$8",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Clérigos Church",
        type: "ATTRACTION",
        latitude: 41.1458,
        longitude: -8.6146,
        description: "Baroque church with a tall bell tower.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$8",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Palácio da Bolsa",
        type: "ATTRACTION",
        latitude: 41.1415,
        longitude: -8.6156,
        description: "Historical neoclassical building.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$12",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Ribeira Square",
        type: "ATTRACTION",
        latitude: 41.1402,
        longitude: -8.6133,
        description: "Historical square by the Douro river.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Zurich",
    country: "Switzerland",
    state: "Zurich",
    latitude: 47.3769,
    longitude: 8.5417,
    description: "Global center for banking and finance, set at the north end of Lake Zurich.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "luxury",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Lake Zurich",
        type: "ATTRACTION",
        latitude: 47.2519,
        longitude: 8.683,
        description: "Large scenic lake offering boat rides.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Grossmünster",
        type: "ATTRACTION",
        latitude: 47.3701,
        longitude: 8.5441,
        description: "Romanesque-style Protestant church.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Fraumünster",
        type: "ATTRACTION",
        latitude: 47.3698,
        longitude: 8.5422,
        description: "Church known for Marc Chagall's stained glass windows.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Bahnhofstrasse",
        type: "ATTRACTION",
        latitude: 47.3725,
        longitude: 8.5385,
        description: "Exclusive shopping avenue.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Kunsthaus Zurich",
        type: "ATTRACTION",
        latitude: 47.3703,
        longitude: 8.5484,
        description: "Major art museum in Switzerland.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$25",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
  {
    name: "Geneva",
    country: "Switzerland",
    state: "Geneva",
    latitude: 46.2044,
    longitude: 6.1432,
    description: "A global city, financial center, and worldwide center for diplomacy.",
    categories: ["Culture", "History", "Sightseeing"],
    tags: ["Iconic", "Historic", "Must-See"],
    bestSeason: "Summer",
    averageBudget: "luxury",
    travelDaysRecommended: 5,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    places: [
      {
        name: "Jet d'Eau",
        type: "ATTRACTION",
        latitude: 46.2074,
        longitude: 6.1559,
        description: "Large fountain in Lake Geneva.",
        activityCategories: ["Landmark"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Palace of Nations",
        type: "ATTRACTION",
        latitude: 46.2266,
        longitude: 6.1396,
        description: "Home of the United Nations Office at Geneva.",
        activityCategories: ["Historical Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$20",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "St Pierre Cathedral",
        type: "ATTRACTION",
        latitude: 46.2012,
        longitude: 6.1485,
        description: "Historic cathedral known for its Protestant history.",
        activityCategories: ["Religious Site"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Lake Geneva",
        type: "ATTRACTION",
        latitude: 46.4312,
        longitude: 6.5298,
        description: "Deep lake on the north side of the Alps.",
        activityCategories: ["Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
      {
        name: "Patek Philippe Museum",
        type: "ATTRACTION",
        latitude: 46.1994,
        longitude: 6.1352,
        description: "Museum of Swiss watchmaking.",
        activityCategories: ["Museum"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$15",
        imageUrl: "https://images.unsplash.com/photo-1543305619-3c35f793e50f"
      },
    ]
  },
];

export default europeDestinations;
