export default [
  {
    name: "Dubai",
    country: "United Arab Emirates",
    state: "Dubai",
    latitude: 25.2048,
    longitude: 55.2708,
    description: "A city of skyscrapers, ports, and beaches, where big business takes place alongside sun-seeking tourism.",
    categories: ["City", "Luxury", "Shopping", "Entertainment"],
    tags: ["Iconic", "Modern", "Skyscrapers", "Beaches"],
    bestSeason: "Winter",
    averageBudget: "luxury",
    travelDaysRecommended: 5,
    planningScore: 95,
    heroImageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    places: [
      {
        name: "Burj Khalifa",
        type: "ATTRACTION",
        latitude: 25.1972,
        longitude: 55.2744,
        description: "The tallest building in the world, offering spectacular views from its observation decks.",
        activityCategories: ["Landmark", "Observation Deck"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$45",
        imageUrl: "https://images.unsplash.com/photo-1597659806240-d7674036ad08"
      },
      {
        name: "The Dubai Mall",
        type: "ATTRACTION",
        latitude: 25.1973,
        longitude: 55.2793,
        description: "One of the world's largest shopping malls, featuring over 1,200 retail outlets and entertainment venues.",
        activityCategories: ["Shopping", "Entertainment"],
        estimatedVisitDuration: "4 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1582719202047-76d33db8667a"
      },
      {
        name: "Palm Jumeirah",
        type: "ATTRACTION",
        latitude: 25.1124,
        longitude: 55.1390,
        description: "An iconic artificial archipelago known for luxury hotels, upscale apartments, and global restaurants.",
        activityCategories: ["Island", "Landmark"],
        estimatedVisitDuration: "3 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1522619053229-37332ee4b46b"
      },
      {
        name: "Burj Al Arab",
        type: "HOTEL",
        latitude: 25.1412,
        longitude: 55.1853,
        description: "A luxury hotel celebrated for its sail-shaped silhouette and opulent interiors.",
        activityCategories: ["Architecture", "Luxury"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "Free to view outside",
        imageUrl: "https://images.unsplash.com/photo-1621532159157-190d65b16982"
      },
      {
        name: "Dubai Museum",
        type: "ATTRACTION",
        latitude: 25.2633,
        longitude: 55.2972,
        description: "Located in the Al Fahidi Fort, it presents the traditional way of life in the Emirate of Dubai.",
        activityCategories: ["Museum", "History"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "$1",
        imageUrl: "https://images.unsplash.com/photo-1601614763375-397a6125ebf9"
      },
      {
        name: "The Dubai Fountain",
        type: "ATTRACTION",
        latitude: 25.1953,
        longitude: 55.2764,
        description: "A choreographed fountain system set on the Burj Khalifa Lake.",
        activityCategories: ["Entertainment", "Fountain Show"],
        estimatedVisitDuration: "0.5 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1549427357-128e469d41d1"
      },
      {
        name: "Dubai Marina",
        type: "ATTRACTION",
        latitude: 25.0780,
        longitude: 55.1360,
        description: "An affluent residential neighborhood known for The Beach at JBR and luxury yacht cruises.",
        activityCategories: ["Waterfront", "Walking"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1518684079-3c830dcef090"
      },
      {
        name: "Dubai Frame",
        type: "ATTRACTION",
        latitude: 25.2355,
        longitude: 55.3003,
        description: "An architectural landmark in Zabeel Park, holding the record for the largest frame in the world.",
        activityCategories: ["Landmark", "Observation Deck"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "$14",
        imageUrl: "https://images.unsplash.com/photo-1582650507328-56d47b1af206"
      }
    ]
  },
  {
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    state: "Abu Dhabi",
    latitude: 24.4539,
    longitude: 54.3773,
    description: "The capital of the UAE, known for its incredible architectural feats and cultural sites.",
    categories: ["Culture", "History", "Luxury"],
    tags: ["Capital", "Culture", "Architecture", "Islands"],
    bestSeason: "Winter",
    averageBudget: "high",
    travelDaysRecommended: 4,
    planningScore: 90,
    heroImageUrl: "https://images.unsplash.com/photo-1588725832791-24022a16d510",
    places: [
      {
        name: "Sheikh Zayed Grand Mosque",
        type: "ATTRACTION",
        latitude: 24.4128,
        longitude: 54.4750,
        description: "One of the world's largest mosques, an architectural work of art featuring 82 domes.",
        activityCategories: ["Religious Site", "Architecture"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1563821015091-886d34b3dc05"
      },
      {
        name: "Louvre Abu Dhabi",
        type: "ATTRACTION",
        latitude: 24.5338,
        longitude: 54.3986,
        description: "An art and civilization museum situated on the Saadiyat Island Cultural District.",
        activityCategories: ["Museum", "Art"],
        estimatedVisitDuration: "3 hours",
        ticketPrice: "$17",
        imageUrl: "https://images.unsplash.com/photo-1544431945-812046db4cc0"
      },
      {
        name: "Ferrari World Abu Dhabi",
        type: "ATTRACTION",
        latitude: 24.4839,
        longitude: 54.6071,
        description: "A mostly indoors amusement park on Yas Island, home to the fastest rollercoaster in the world.",
        activityCategories: ["Theme Park", "Entertainment"],
        estimatedVisitDuration: "5 hours",
        ticketPrice: "$85",
        imageUrl: "https://images.unsplash.com/photo-1506199342790-27690623ce1b"
      },
      {
        name: "Qasr Al Watan",
        type: "ATTRACTION",
        latitude: 24.4608,
        longitude: 54.3168,
        description: "The Presidential Palace of the UAE, open to the public to explore its majestic halls.",
        activityCategories: ["Palace", "Culture"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$18",
        imageUrl: "https://images.unsplash.com/photo-1629800725586-2245b0a33a39"
      },
      {
        name: "Yas Marina Circuit",
        type: "ATTRACTION",
        latitude: 24.4697,
        longitude: 54.6033,
        description: "The venue for the Abu Dhabi Grand Prix, offering track days and driving experiences.",
        activityCategories: ["Motorsports", "Sports Venue"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Varies",
        imageUrl: "https://images.unsplash.com/photo-1614030612185-1bf8d022b7d5"
      },
      {
        name: "Emirates Palace",
        type: "HOTEL",
        latitude: 24.4616,
        longitude: 54.3173,
        description: "A luxury five-star hotel known for its lavish decor and beautiful private beach.",
        activityCategories: ["Luxury", "Architecture"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "Free to visit public areas",
        imageUrl: "https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0"
      },
      {
        name: "Saadiyat Island",
        type: "ATTRACTION",
        latitude: 24.5422,
        longitude: 54.4332,
        description: "A tourism-cultural project for nature and Emirati heritage and culture.",
        activityCategories: ["Island", "Culture"],
        estimatedVisitDuration: "3 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1506459225024-1428097a7e18"
      },
      {
        name: "Warner Bros. World Abu Dhabi",
        type: "ATTRACTION",
        latitude: 24.4913,
        longitude: 54.6006,
        description: "An indoor amusement park featuring rides and shows based on Warner Bros. properties.",
        activityCategories: ["Theme Park", "Family"],
        estimatedVisitDuration: "5 hours",
        ticketPrice: "$90",
        imageUrl: "https://images.unsplash.com/photo-1513880989635-6eb491ce7f5b"
      }
    ]
  },
  {
    name: "Sharjah",
    country: "United Arab Emirates",
    state: "Sharjah",
    latitude: 25.3463,
    longitude: 55.4209,
    description: "Considered the cultural capital of the UAE, boasting impressive museums, heritage areas, and art festivals.",
    categories: ["Culture", "History", "Family"],
    tags: ["Cultural Capital", "Museums", "Heritage"],
    bestSeason: "Winter",
    averageBudget: "medium",
    travelDaysRecommended: 3,
    planningScore: 82,
    heroImageUrl: "https://images.unsplash.com/photo-1601614763375-397a6125ebf9",
    places: [
      {
        name: "Sharjah Museum of Islamic Civilization",
        type: "ATTRACTION",
        latitude: 25.3644,
        longitude: 55.3852,
        description: "A museum showcasing over 5,000 artifacts from the Islamic world.",
        activityCategories: ["Museum", "Culture"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$3",
        imageUrl: "https://images.unsplash.com/photo-1595183495449-74d32e6fb1c4"
      },
      {
        name: "Al Noor Island",
        type: "ATTRACTION",
        latitude: 25.3341,
        longitude: 55.3840,
        description: "A tranquil island featuring landscaped gardens, a butterfly house, and art sculptures.",
        activityCategories: ["Nature", "Park"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$14",
        imageUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b"
      },
      {
        name: "Sharjah Art Museum",
        type: "ATTRACTION",
        latitude: 25.3621,
        longitude: 55.3843,
        description: "One of the largest art exhibitions in the Gulf region, featuring modern and contemporary Arab art.",
        activityCategories: ["Museum", "Art"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1572949645841-094f3a9c4c94"
      },
      {
        name: "Al Majaz Waterfront",
        type: "ATTRACTION",
        latitude: 25.3314,
        longitude: 55.3852,
        description: "A family-friendly leisure destination with restaurants, a splash park, and a musical fountain.",
        activityCategories: ["Waterfront", "Entertainment"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1518005020951-eccb494ad742"
      },
      {
        name: "Sharjah Aquarium",
        type: "ATTRACTION",
        latitude: 25.3333,
        longitude: 55.3582,
        description: "An aquarium featuring the diverse marine life of the UAE's coasts.",
        activityCategories: ["Aquarium", "Family"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "$7",
        imageUrl: "https://images.unsplash.com/photo-1535591273668-578e31182c4f"
      },
      {
        name: "Blue Souk",
        type: "ATTRACTION",
        latitude: 25.3503,
        longitude: 55.3831,
        description: "The main shopping hub and one of the most impressive landmarks in Sharjah.",
        activityCategories: ["Shopping", "Market"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1621252179027-9d6dc6db9d1d"
      },
      {
        name: "Sharjah Desert Park",
        type: "ATTRACTION",
        latitude: 25.2818,
        longitude: 55.6985,
        description: "A complex including a Natural History Museum, Botanical Museum, and Wildlife Centre.",
        activityCategories: ["Nature", "Wildlife"],
        estimatedVisitDuration: "3 hours",
        ticketPrice: "$6",
        imageUrl: "https://images.unsplash.com/photo-1615598692750-f6c6d042f4c3"
      },
      {
        name: "Al Qasba",
        type: "ATTRACTION",
        latitude: 25.3235,
        longitude: 55.3752,
        description: "A commercial complex offering entertainment, restaurants, and the Eye of the Emirates Ferris wheel.",
        activityCategories: ["Entertainment", "Dining"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1614028097071-8bcba358df8a"
      }
    ]
  },
  {
    name: "Ras Al Khaimah",
    country: "United Arab Emirates",
    state: "Ras Al Khaimah",
    latitude: 25.7895,
    longitude: 55.9432,
    description: "The northernmost emirate, known for its diverse landscape of mountains, desert, and coastline.",
    categories: ["Nature", "Adventure", "History"],
    tags: ["Mountains", "Adventure", "Beaches"],
    bestSeason: "Winter",
    averageBudget: "medium",
    travelDaysRecommended: 3,
    planningScore: 85,
    heroImageUrl: "https://images.unsplash.com/photo-1549427357-128e469d41d1",
    places: [
      {
        name: "Jebel Jais",
        type: "ATTRACTION",
        latitude: 25.9388,
        longitude: 56.1417,
        description: "The highest peak in the UAE, offering spectacular views and home to the world's longest zipline.",
        activityCategories: ["Nature", "Adventure"],
        estimatedVisitDuration: "4 hours",
        ticketPrice: "Free (Activities extra)",
        imageUrl: "https://images.unsplash.com/photo-1579564619438-e6d1c81ef4cb"
      },
      {
        name: "National Museum of Ras Al Khaimah",
        type: "ATTRACTION",
        latitude: 25.7946,
        longitude: 55.9427,
        description: "Housed in a former fort, the museum exhibits historical and archaeological artifacts.",
        activityCategories: ["Museum", "History"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "$2",
        imageUrl: "https://images.unsplash.com/photo-1563806950-48e02ea5ed2e"
      },
      {
        name: "Dhayah Fort",
        type: "ATTRACTION",
        latitude: 25.8824,
        longitude: 56.0601,
        description: "A 16th-century mud-brick fort offering panoramic views of the surrounding palm gardens and sea.",
        activityCategories: ["Historical Site", "Viewpoint"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0"
      },
      {
        name: "Al Hamra Mall",
        type: "ATTRACTION",
        latitude: 25.7118,
        longitude: 55.7940,
        description: "A popular shopping destination in Ras Al Khaimah with international and local brands.",
        activityCategories: ["Shopping"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1582719202047-76d33db8667a"
      },
      {
        name: "Jazirat Al Hamra",
        type: "ATTRACTION",
        latitude: 25.7088,
        longitude: 55.7960,
        description: "An abandoned traditional pearling village offering a glimpse into the region's past.",
        activityCategories: ["Historical Site", "Ghost Town"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1549427357-128e469d41d1"
      },
      {
        name: "Suwaidi Pearls",
        type: "ATTRACTION",
        latitude: 25.8690,
        longitude: 56.0270,
        description: "A pearl farm providing insights into the historical pearl diving industry of the UAE.",
        activityCategories: ["Culture", "Tour"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$60",
        imageUrl: "https://images.unsplash.com/photo-1621532159157-190d65b16982"
      },
      {
        name: "Khatt Springs",
        type: "ATTRACTION",
        latitude: 25.6111,
        longitude: 56.0046,
        description: "Hot mineral springs famous for their therapeutic properties.",
        activityCategories: ["Wellness", "Nature"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$5",
        imageUrl: "https://images.unsplash.com/photo-1601614763375-397a6125ebf9"
      },
      {
        name: "Saqr Park",
        type: "ATTRACTION",
        latitude: 25.6888,
        longitude: 55.9754,
        description: "The largest public park in Ras Al Khaimah, ideal for family picnics and outdoor activities.",
        activityCategories: ["Park", "Family"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$1",
        imageUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b"
      }
    ]
  },
  {
    name: "Fujairah",
    country: "United Arab Emirates",
    state: "Fujairah",
    latitude: 25.1288,
    longitude: 56.3265,
    description: "The only emirate with a coastline solely on the Gulf of Oman, famous for its beaches and mountains.",
    categories: ["Nature", "Beach", "History"],
    tags: ["Diving", "Mountains", "Beaches", "Forts"],
    bestSeason: "Winter",
    averageBudget: "medium",
    travelDaysRecommended: 2,
    planningScore: 80,
    heroImageUrl: "https://images.unsplash.com/photo-1601614763375-397a6125ebf9",
    places: [
      {
        name: "Fujairah Fort",
        type: "ATTRACTION",
        latitude: 25.1388,
        longitude: 56.3364,
        description: "One of the oldest and largest forts in the UAE, dating back to the 16th century.",
        activityCategories: ["Historical Site", "Architecture"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0"
      },
      {
        name: "Al Bidyah Mosque",
        type: "ATTRACTION",
        latitude: 25.4389,
        longitude: 56.3547,
        description: "The oldest known functioning mosque in the UAE, known for its unique four-domed design.",
        activityCategories: ["Religious Site", "Historical Site"],
        estimatedVisitDuration: "0.5 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1563821015091-886d34b3dc05"
      },
      {
        name: "Snoopy Island",
        type: "ATTRACTION",
        latitude: 25.4925,
        longitude: 56.3631,
        description: "A popular spot for snorkeling and diving, named for its resemblance to the cartoon dog Snoopy.",
        activityCategories: ["Beach", "Water Sports"],
        estimatedVisitDuration: "3 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1506459225024-1428097a7e18"
      },
      {
        name: "Fujairah Museum",
        type: "ATTRACTION",
        latitude: 25.1325,
        longitude: 56.3355,
        description: "A museum showcasing archaeological finds and depicting traditional life in the emirate.",
        activityCategories: ["Museum", "History"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "$2",
        imageUrl: "https://images.unsplash.com/photo-1595183495449-74d32e6fb1c4"
      },
      {
        name: "Ain Al Madhab Gardens",
        type: "ATTRACTION",
        latitude: 25.1323,
        longitude: 56.3075,
        description: "A park surrounding mineral springs, popular for its warm pools and picnic areas.",
        activityCategories: ["Park", "Wellness"],
        estimatedVisitDuration: "2 hours",
        ticketPrice: "$1",
        imageUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b"
      },
      {
        name: "Sheikh Zayed Mosque Fujairah",
        type: "ATTRACTION",
        latitude: 25.1226,
        longitude: 56.3262,
        description: "The second largest mosque in the UAE, an impressive structure with 65 domes and six minarets.",
        activityCategories: ["Religious Site", "Architecture"],
        estimatedVisitDuration: "1 hour",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1563821015091-886d34b3dc05"
      },
      {
        name: "Fujairah Heritage Village",
        type: "ATTRACTION",
        latitude: 25.1340,
        longitude: 56.3360,
        description: "An open-air museum detailing the region's traditional lifestyle, including old farming methods.",
        activityCategories: ["Culture", "History"],
        estimatedVisitDuration: "1.5 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0"
      },
      {
        name: "Wadi Wurayah",
        type: "ATTRACTION",
        latitude: 25.3965,
        longitude: 56.2612,
        description: "A national park featuring natural pools, waterfalls, and diverse flora and fauna.",
        activityCategories: ["Nature", "Hiking"],
        estimatedVisitDuration: "3 hours",
        ticketPrice: "Free",
        imageUrl: "https://images.unsplash.com/photo-1579564619438-e6d1c81ef4cb"
      }
    ]
  }
];
